import SwiftUI

/// Sheet that lists the user's whole programme — port of ProgrammeModal.jsx.
/// Two modes: "auto" (programme generated by onboarding, shows a 7-day
/// schedule grid + all sessions as expandable cards) and "imported"
/// (multi-week programme with a tab strip across weeks).
///
/// Backed by `app.activeProgramme` which holds either shape via its
/// `data: ProgrammeData?` blob.
struct ProgrammeModalView: View {
    @EnvironmentObject var app: AppState
    @Environment(\.dismiss) private var dismiss

    @State private var selectedWeek: Int = 1
    /// Track which session card is expanded by `day` string — using the
    /// `ProgrammeSession.id` computed UUID doesn't work because it returns
    /// a new UUID each access (pre-existing in Models.swift).
    @State private var expandedSessionDay: String? = nil

    private var ar: Bool { app.language == "ar" }

    /// Imported programme has weeks; auto programme is a flat array.
    /// For now the only data we have is `app.activeProgramme` which holds
    /// either shape via its `data: ProgrammeData?`.
    private var isImported: Bool {
        guard let weeks = app.activeProgramme?.data?.weeks else { return false }
        return weeks.count > 1
    }

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: 20) {
                    header
                    if let weeks = app.activeProgramme?.data?.weeks, !weeks.isEmpty {
                        if isImported {
                            importedBody(weeks: weeks)
                        } else {
                            autoBody(week: weeks.first!)
                        }
                    } else {
                        emptyState
                    }
                    Spacer(minLength: 24)
                }
                .padding(.horizontal, 20)
                .padding(.top, 20)
            }
            .background(HexTheme.bg.ignoresSafeArea())
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Button { dismiss() } label: {
                        Image(systemName: "xmark.circle.fill")
                            .font(.system(size: 22))
                            .foregroundColor(HexTheme.dim)
                    }
                }
            }
            .navigationBarTitleDisplayMode(.inline)
        }
    }

    // MARK: - Header

    private var header: some View {
        VStack(alignment: .leading, spacing: 6) {
            Text(isImported
                 ? (ar ? "برنامج مستورد" : "IMPORTED PROGRAMME")
                 : (ar ? "برنامجك" : "YOUR PROGRAMME"))
                .font(.system(size: 10, weight: .heavy))
                .kerning(ar ? 0 : 1.2)
                .foregroundColor(HexTheme.accent)
            Text(app.activeProgramme?.name ?? (ar ? "تلقائي" : "Auto-generated"))
                .font(.system(size: 20, weight: .heavy))
                .kerning(ar ? 0 : -0.4)
                .foregroundColor(HexTheme.text)
        }
    }

    private var emptyState: some View {
        VStack(spacing: 12) {
            Image(systemName: "doc.text")
                .font(.system(size: 36))
                .foregroundColor(HexTheme.mute)
            Text(ar
                 ? "لا يوجد برنامج بعد"
                 : "No programme yet")
                .font(.system(size: 15, weight: .heavy))
                .foregroundColor(HexTheme.text)
            Text(ar
                 ? "ابنِ برنامجك أو استورد واحداً من شاشة الحساب."
                 : "Build a programme or import one from the Profile tab.")
                .font(.system(size: 13))
                .foregroundColor(HexTheme.dim)
                .multilineTextAlignment(.center)
                .padding(.horizontal, 16)
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 40)
    }

    // MARK: - Auto mode (one-week schedule + session list)

    @ViewBuilder
    private func autoBody(week: ProgrammeWeek) -> some View {
        scheduleGrid(sessions: week.sessions)
        sectionLabel(ar ? "كل الجلسات" : "ALL SESSIONS")
        VStack(spacing: 8) {
            ForEach(week.sessions) { s in
                sessionCard(session: s, isToday: false)
            }
        }
        Text(ar
             ? "يدور البرنامج تلقائياً بعد إكمال جميع الجلسات."
             : "Programme cycles automatically after completing all sessions.")
            .font(.system(size: 11))
            .foregroundColor(HexTheme.mute)
            .frame(maxWidth: .infinity)
            .padding(.top, 12)
    }

    private func scheduleGrid(sessions: [ProgrammeSession]) -> some View {
        let dayLetters = ["M", "T", "W", "T", "F", "S", "S"]
        return VStack(alignment: .leading, spacing: 8) {
            sectionLabel(ar ? "الجدول" : "SCHEDULE")
            HStack(spacing: 4) {
                ForEach(0..<7, id: \.self) { i in
                    let s = i < sessions.count ? sessions[i] : nil
                    let isTraining = s != nil
                    VStack(spacing: 4) {
                        Text(dayLetters[i])
                            .font(.system(size: 9))
                            .foregroundColor(HexTheme.mute)
                        Text(isTraining
                             ? String(s?.name.prefix(1) ?? "T")
                             : "—")
                            .font(.system(size: 10, weight: .heavy))
                            .foregroundColor(isTraining ? HexTheme.accent : HexTheme.mute)
                            .frame(maxWidth: .infinity)
                            .frame(height: 32)
                            .background(
                                RoundedRectangle(cornerRadius: 6, style: .continuous)
                                    .fill(isTraining ? HexTheme.accent.opacity(0.15) : HexTheme.surface2)
                            )
                            .overlay(
                                RoundedRectangle(cornerRadius: 6, style: .continuous)
                                    .stroke(isTraining ? HexTheme.accent.opacity(0.3) : HexTheme.border, lineWidth: 1)
                            )
                    }
                }
            }
        }
    }

    // MARK: - Imported mode (week tabs + day list)

    @ViewBuilder
    private func importedBody(weeks: [ProgrammeWeek]) -> some View {
        // Week tab strip
        ScrollView(.horizontal, showsIndicators: false) {
            HStack(spacing: 6) {
                ForEach(weeks, id: \.weekNumber) { w in
                    let active = selectedWeek == w.weekNumber
                    Button {
                        withAnimation(.spring(response: 0.35)) {
                            selectedWeek = w.weekNumber
                        }
                    } label: {
                        Text("W\(w.weekNumber)")
                            .font(.system(size: 12, weight: .heavy))
                            .foregroundColor(active ? .black : HexTheme.dim)
                            .padding(.horizontal, 14)
                            .padding(.vertical, 6)
                            .background(
                                Capsule().fill(active ? HexTheme.accent : HexTheme.surface2)
                            )
                            .overlay(
                                Capsule().stroke(active ? HexTheme.accent : HexTheme.border,
                                                 lineWidth: 1.5)
                            )
                    }
                    .buttonStyle(.plain)
                }
            }
        }

        // Day list for selected week
        if let wk = weeks.first(where: { $0.weekNumber == selectedWeek }) {
            VStack(spacing: 0) {
                ForEach(["mon","tue","wed","thu","fri","sat","sun"], id: \.self) { dayKey in
                    let s = wk.sessions.first(where: { $0.day == dayKey })
                    HStack(spacing: 10) {
                        Text(dayLabel(dayKey).capitalized)
                            .font(.system(size: 12, weight: .heavy))
                            .foregroundColor(s == nil ? HexTheme.mute : HexTheme.accent)
                            .frame(width: 50, alignment: .leading)
                        Text(s?.name ?? (ar ? "راحة" : "Rest"))
                            .font(.system(size: 13))
                            .foregroundColor(s == nil ? HexTheme.mute : HexTheme.text)
                        Spacer()
                    }
                    .padding(.vertical, 8)
                    .overlay(
                        Rectangle().fill(HexTheme.border).frame(height: 1),
                        alignment: .bottom
                    )
                }
            }

            sectionLabel((ar ? "جلسات — الأسبوع " : "SESSIONS — WEEK ") + "\(selectedWeek)")
            VStack(spacing: 8) {
                ForEach(wk.sessions) { s in
                    sessionCard(session: s, isToday: false)
                }
            }
        }
    }

    private func dayLabel(_ key: String) -> String {
        switch key {
        case "mon": return ar ? "اثنين"  : "Mon"
        case "tue": return ar ? "ثلاثاء"  : "Tue"
        case "wed": return ar ? "أربعاء"  : "Wed"
        case "thu": return ar ? "خميس"   : "Thu"
        case "fri": return ar ? "جمعة"    : "Fri"
        case "sat": return ar ? "سبت"     : "Sat"
        case "sun": return ar ? "أحد"     : "Sun"
        default: return key
        }
    }

    // MARK: - Session card

    private func sessionCard(session: ProgrammeSession, isToday: Bool) -> some View {
        let expanded = expandedSessionDay == session.day
        return VStack(spacing: 0) {
            Button {
                withAnimation(.spring(response: 0.35)) {
                    expandedSessionDay = expanded ? nil : session.day
                }
            } label: {
                HStack(spacing: 10) {
                    Text(String(session.name.prefix(1)))
                        .font(.system(size: 11, weight: .heavy))
                        .foregroundColor(isToday ? .black : HexTheme.dim)
                        .frame(width: 30, height: 30)
                        .background(
                            RoundedRectangle(cornerRadius: 8, style: .continuous)
                                .fill(isToday ? HexTheme.accent : HexTheme.surface)
                        )
                    VStack(alignment: .leading, spacing: 1) {
                        Text(session.name)
                            .font(.system(size: 14, weight: .heavy))
                            .foregroundColor(HexTheme.text)
                        Text(ar
                             ? "\(session.exercises.count) تمارين · ~\(session.exercises.count * 6) د"
                             : "\(session.exercises.count) exercises · ~\(session.exercises.count * 6) min")
                            .font(.system(size: 11))
                            .foregroundColor(HexTheme.dim)
                    }
                    Spacer()
                    Image(systemName: expanded ? "chevron.up" : "chevron.down")
                        .font(.system(size: 11, weight: .semibold))
                        .foregroundColor(HexTheme.mute)
                }
                .padding(.horizontal, 14)
                .padding(.vertical, 12)
            }
            .buttonStyle(.plain)

            if expanded {
                VStack(spacing: 0) {
                    Rectangle().fill(HexTheme.border).frame(height: 1)
                    VStack(spacing: 0) {
                        ForEach(session.exercises) { ex in
                            exerciseRow(ex: ex)
                        }
                    }
                    .padding(.horizontal, 14)
                }
                .transition(.opacity)
            }
        }
        .background(
            RoundedRectangle(cornerRadius: 12, style: .continuous)
                .fill(HexTheme.surface2)
        )
        .overlay(
            RoundedRectangle(cornerRadius: 12, style: .continuous)
                .stroke(isToday ? HexTheme.accent : HexTheme.border, lineWidth: 1.5)
        )
    }

    private func exerciseRow(ex: Exercise) -> some View {
        HStack(spacing: 8) {
            Text(ex.tag ?? "acc")
                .font(.system(size: 10, weight: .heavy))
                .foregroundColor(HexTheme.mute)
                .padding(.horizontal, 6)
                .padding(.vertical, 2)
                .background(
                    RoundedRectangle(cornerRadius: 4)
                        .fill(HexTheme.surface)
                )
            Text(ex.name)
                .font(.system(size: 13))
                .foregroundColor(HexTheme.text)
                .lineLimit(1)
                .frame(maxWidth: .infinity, alignment: .leading)
            Text("\(ex.sets)×\(ex.reps)")
                .font(.system(size: 11))
                .foregroundColor(HexTheme.dim)
            Text(ex.weight.map { $0 <= 0 ? "BW" : "\(Int($0))kg" } ?? "—")
                .font(.system(size: 11, weight: .heavy))
                .foregroundColor(HexTheme.accent)
        }
        .padding(.vertical, 8)
        .overlay(
            Rectangle().fill(HexTheme.border).frame(height: 1),
            alignment: .bottom
        )
    }

    private func sectionLabel(_ text: String) -> some View {
        Text(text)
            .font(.system(size: 11, weight: .heavy))
            .kerning(ar ? 0 : 0.9)
            .foregroundColor(HexTheme.dim)
            .frame(maxWidth: .infinity, alignment: .leading)
    }
}
